name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI build & test

    strategy:
      matrix:
        node-version: [16, 18, latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies & Build output
        run: yarn --network-concurrency 8 || yarn --check-files --cache-folder .ycache && rm -rf .ycache

      - name: Run tests
        run: yarn test

      - name: Check for lint errors
        run: yarn lint
